apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-drv-conf-map
data:
  spark.properties: |
    spark.kubernetes.driverEnv.SPARK_MASTER_URL=spark\://172.31.36.235\:30086
    spark.app.name=spark-pi
    spark.executor.cores=1
    spark.kubernetes.resource.type=java
    spark.submit.deployMode=cluster
    spark.driver.blockManager.port=7079
    spark.kubernetes.container.image=bitnami/spark\:3
    spark.kubernetes.memoryOverheadFactor=0.1
    spark.kubernetes.submitInDriver=true
    spark.kubernetes.authenticate.driver.serviceAccountName=spark
